using Nakshatra.Shared.Models;

namespace Nakshatra.Media.Service;

/// <summary>
/// Local file-system backed media storage. Keys are generated by the service (never taken from the
/// client) and every resolved path is verified to stay inside the storage root.
/// </summary>
public class MediaStorage
{
    private readonly string _root;

    public MediaStorage(IConfiguration configuration)
    {
        var configured = configuration["Media:StorageRoot"];
        _root = Path.GetFullPath(string.IsNullOrWhiteSpace(configured)
            ? Path.Combine(AppContext.BaseDirectory, "media-storage")
            : configured);
        Directory.CreateDirectory(_root);
    }

    public string OriginalPath(string assetId, string extension) => Resolve(Path.Combine(assetId, $"original{extension}"));

    public string RenditionDirectory(string assetId) => Resolve(Path.Combine(assetId, "renditions"));

    public string RenditionPath(string assetId, string renditionName, string format)
        => Resolve(Path.Combine(assetId, "renditions", $"{renditionName}.{format}"));

    public async Task<long> SaveAsync(string path, Stream content, CancellationToken ct)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        await using var file = File.Create(path);
        await content.CopyToAsync(file, ct);
        return file.Length;
    }

    /// <summary>Resolves a path under the storage root, rejecting traversal outside of it.</summary>
    public string Resolve(string relativePath)
    {
        var fullPath = Path.GetFullPath(Path.Combine(_root, relativePath));
        if (!fullPath.StartsWith(_root + Path.DirectorySeparatorChar, StringComparison.Ordinal) && fullPath != _root)
        {
            throw new UnauthorizedAccessException("Resolved media path escapes the storage root.");
        }

        return fullPath;
    }
}

public static class MediaContentTypes
{
    private static readonly Dictionary<string, (MediaKind Kind, string Extension)> Allowed = new(StringComparer.OrdinalIgnoreCase)
    {
        ["image/jpeg"] = (MediaKind.Image, ".jpg"),
        ["image/png"] = (MediaKind.Image, ".png"),
        ["image/webp"] = (MediaKind.Image, ".webp"),
        ["image/gif"] = (MediaKind.Image, ".gif"),
        ["video/mp4"] = (MediaKind.Video, ".mp4"),
        ["video/quicktime"] = (MediaKind.Video, ".mov"),
        ["video/webm"] = (MediaKind.Video, ".webm")
    };

    public static bool TryResolve(string? contentType, out MediaKind kind, out string extension)
    {
        if (contentType is not null && Allowed.TryGetValue(contentType, out var match))
        {
            kind = match.Kind;
            extension = match.Extension;
            return true;
        }

        kind = default;
        extension = string.Empty;
        return false;
    }

    public static string ContentTypeFor(string format) => format.ToLowerInvariant() switch
    {
        "webp" => "image/webp",
        "jpg" or "jpeg" => "image/jpeg",
        "png" => "image/png",
        "gif" => "image/gif",
        "mp4" => "video/mp4",
        "mov" => "video/quicktime",
        "webm" => "video/webm",
        _ => "application/octet-stream"
    };

    public static IReadOnlyCollection<string> Supported => Allowed.Keys;
}
